services:
  cats-api-8081:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    container_name: cats-api-8081
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  cats-api-8082:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
    container_name: cats-api-8082
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge
