services:
  cats-api:
    build:
      context: ./projects/cats-api
      dockerfile: ./Dockerfile
      target: runtime
    # Ports will be handled by reverse proxy
    expose:
      - "8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 5 # Change this number to scale instances
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M

  reverse-proxy:
    build:
      context: ./projects/reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "4443:8080"
    environment:
      - LB_STRATEGY=${LB_STRATEGY:-roundrobin} # Default to round robin, can be overridden
    depends_on:
      - cats-api
    restart: unless-stopped

networks:
  default:
    driver: bridge
