name: Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out ./... -coverpkg=./...

      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Update coverage badge
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep "total:" | awk '{print $3}')
          echo "Coverage: $COVERAGE"
          # Here you could update the README badge automatically
          # and commit the changes back to the repository

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html
